### ISSUE TITLE
Usar IndexedDB

### ISSUE THREAD

**Issue by fabriciorissetto** [CWIInnovation/parking-lot#4]
Quando abrir o aplicativo buscar todas as placas da api e sincronizar em IndexedDB.

Isso vai ajudar em coisas como: Quando redirecionarmos pra tela de detalhe do motorista passando a placa podemos buscar no indexedDb os detalhes do motorista

**Comment by fjunqueira** [comment]
[done!](https://github.com/CWIInnovation/parking-lot/commit/dda7faeb47b1ff888666b00013fa45912eb9e7a2)
